# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AttoPos.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AttoPos(object):
    def setupUi(self, AttoPos):
        AttoPos.setObjectName("AttoPos")
        AttoPos.setWindowModality(QtCore.Qt.NonModal)
        AttoPos.resize(1060, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AttoPos.sizePolicy().hasHeightForWidth())
        AttoPos.setSizePolicy(sizePolicy)
        AttoPos.setMinimumSize(QtCore.QSize(1060, 600))
        AttoPos.setMaximumSize(QtCore.QSize(1060, 600))
        AttoPos.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AttoPos.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AttoPos)
        self.gridLayout.setObjectName("gridLayout")
        self.contYled = QtWidgets.QLabel(AttoPos)
        self.contYled.setMinimumSize(QtCore.QSize(150, 65))
        self.contYled.setMaximumSize(QtCore.QSize(150, 65))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.contYled.setFont(font)
        self.contYled.setStyleSheet("background-color: rgb(0, 115, 255);\n"
"color: rgb(255, 255, 255);")
        self.contYled.setAlignment(QtCore.Qt.AlignCenter)
        self.contYled.setObjectName("contYled")
        self.gridLayout.addWidget(self.contYled, 3, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setHorizontalSpacing(18)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SyPos = QtWidgets.QDoubleSpinBox(AttoPos)
        self.SyPos.setMinimumSize(QtCore.QSize(270, 110))
        self.SyPos.setMaximumSize(QtCore.QSize(270, 110))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.SyPos.setFont(font)
        self.SyPos.setFrame(True)
        self.SyPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SyPos.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SyPos.setDecimals(1)
        self.SyPos.setMaximum(150.0)
        self.SyPos.setSingleStep(0.5)
        self.SyPos.setProperty("value", 150.0)
        self.SyPos.setObjectName("SyPos")
        self.gridLayout_2.addWidget(self.SyPos, 1, 2, 1, 1)
        self.SxPos = QtWidgets.QDoubleSpinBox(AttoPos)
        self.SxPos.setMinimumSize(QtCore.QSize(270, 110))
        self.SxPos.setMaximumSize(QtCore.QSize(270, 110))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.SxPos.setFont(font)
        self.SxPos.setFrame(True)
        self.SxPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SxPos.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SxPos.setDecimals(1)
        self.SxPos.setMaximum(150.0)
        self.SxPos.setSingleStep(0.5)
        self.SxPos.setProperty("value", 150.0)
        self.SxPos.setObjectName("SxPos")
        self.gridLayout_2.addWidget(self.SxPos, 0, 2, 1, 1)
        self.SzPos = QtWidgets.QDoubleSpinBox(AttoPos)
        self.SzPos.setMinimumSize(QtCore.QSize(270, 100))
        self.SzPos.setMaximumSize(QtCore.QSize(270, 110))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.SzPos.setFont(font)
        self.SzPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SzPos.setDecimals(1)
        self.SzPos.setMaximum(150.0)
        self.SzPos.setSingleStep(0.5)
        self.SzPos.setProperty("value", 150.0)
        self.SzPos.setObjectName("SzPos")
        self.gridLayout_2.addWidget(self.SzPos, 2, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label2_4 = QtWidgets.QLabel(AttoPos)
        self.label2_4.setMinimumSize(QtCore.QSize(85, 60))
        self.label2_4.setMaximumSize(QtCore.QSize(85, 120))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(34)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label2_4.setFont(font)
        self.label2_4.setStyleSheet("")
        self.label2_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_4.setObjectName("label2_4")
        self.verticalLayout_9.addWidget(self.label2_4)
        self.SxGnd = QtWidgets.QCheckBox(AttoPos)
        self.SxGnd.setObjectName("SxGnd")
        self.verticalLayout_9.addWidget(self.SxGnd)
        self.SxDeactivate = QtWidgets.QCheckBox(AttoPos)
        self.SxDeactivate.setObjectName("SxDeactivate")
        self.verticalLayout_9.addWidget(self.SxDeactivate)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label2_5 = QtWidgets.QLabel(AttoPos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_5.sizePolicy().hasHeightForWidth())
        self.label2_5.setSizePolicy(sizePolicy)
        self.label2_5.setMinimumSize(QtCore.QSize(85, 60))
        self.label2_5.setMaximumSize(QtCore.QSize(85, 120))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(34)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label2_5.setFont(font)
        self.label2_5.setStyleSheet("")
        self.label2_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_5.setObjectName("label2_5")
        self.verticalLayout_10.addWidget(self.label2_5)
        self.SyGnd = QtWidgets.QCheckBox(AttoPos)
        self.SyGnd.setObjectName("SyGnd")
        self.verticalLayout_10.addWidget(self.SyGnd)
        self.SyDeactivate = QtWidgets.QCheckBox(AttoPos)
        self.SyDeactivate.setObjectName("SyDeactivate")
        self.verticalLayout_10.addWidget(self.SyDeactivate)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(AttoPos)
        self.label_6.setMinimumSize(QtCore.QSize(85, 60))
        self.label_6.setMaximumSize(QtCore.QSize(85, 120))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(34)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.SzGnd = QtWidgets.QCheckBox(AttoPos)
        self.SzGnd.setObjectName("SzGnd")
        self.verticalLayout_11.addWidget(self.SzGnd)
        self.SzDeactivate = QtWidgets.QCheckBox(AttoPos)
        self.SzDeactivate.setObjectName("SzDeactivate")
        self.verticalLayout_11.addWidget(self.SzDeactivate)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(AttoPos)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.SstepSize = QtWidgets.QDoubleSpinBox(AttoPos)
        self.SstepSize.setMinimumSize(QtCore.QSize(90, 45))
        self.SstepSize.setMaximumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.SstepSize.setFont(font)
        self.SstepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SstepSize.setDecimals(1)
        self.SstepSize.setMinimum(0.1)
        self.SstepSize.setMaximum(10.0)
        self.SstepSize.setSingleStep(0.1)
        self.SstepSize.setProperty("value", 1.0)
        self.SstepSize.setObjectName("SstepSize")
        self.horizontalLayout_2.addWidget(self.SstepSize)
        self.label_4 = QtWidgets.QLabel(AttoPos)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_20 = QtWidgets.QLabel(AttoPos)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.label_22 = QtWidgets.QLabel(AttoPos)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_23 = QtWidgets.QLabel(AttoPos)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.label = QtWidgets.QLabel(AttoPos)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AttoPos)
        self.label_2.setMinimumSize(QtCore.QSize(300, 70))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(AttoPos)
        self.label_5.setMinimumSize(QtCore.QSize(458, 70))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PxAmp = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PxAmp.setMinimumSize(QtCore.QSize(105, 39))
        self.PxAmp.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PxAmp.setFont(font)
        self.PxAmp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PxAmp.setDecimals(1)
        self.PxAmp.setMinimum(0.1)
        self.PxAmp.setMaximum(60.0)
        self.PxAmp.setSingleStep(0.1)
        self.PxAmp.setProperty("value", 40.0)
        self.PxAmp.setObjectName("PxAmp")
        self.gridLayout_3.addWidget(self.PxAmp, 2, 2, 1, 1)
        self.PxFreq = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PxFreq.setMinimumSize(QtCore.QSize(105, 39))
        self.PxFreq.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PxFreq.setFont(font)
        self.PxFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PxFreq.setDecimals(0)
        self.PxFreq.setMinimum(1.0)
        self.PxFreq.setMaximum(600.0)
        self.PxFreq.setProperty("value", 100.0)
        self.PxFreq.setObjectName("PxFreq")
        self.gridLayout_3.addWidget(self.PxFreq, 3, 2, 1, 1)
        self.PzAmp = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PzAmp.setMinimumSize(QtCore.QSize(105, 39))
        self.PzAmp.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PzAmp.setFont(font)
        self.PzAmp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PzAmp.setDecimals(1)
        self.PzAmp.setMinimum(0.1)
        self.PzAmp.setMaximum(60.0)
        self.PzAmp.setSingleStep(0.1)
        self.PzAmp.setProperty("value", 40.0)
        self.PzAmp.setObjectName("PzAmp")
        self.gridLayout_3.addWidget(self.PzAmp, 2, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(AttoPos)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(AttoPos)
        self.label_9.setMinimumSize(QtCore.QSize(106, 39))
        self.label_9.setMaximumSize(QtCore.QSize(2000, 39))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(AttoPos)
        self.label_10.setMinimumSize(QtCore.QSize(106, 39))
        self.label_10.setMaximumSize(QtCore.QSize(2000, 39))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PyContUp = QtWidgets.QToolButton(AttoPos)
        self.PyContUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PyContUp.setMaximumSize(QtCore.QSize(75, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ArrowUp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PyContUp.setIcon(icon1)
        self.PyContUp.setIconSize(QtCore.QSize(35, 35))
        self.PyContUp.setObjectName("PyContUp")
        self.verticalLayout_6.addWidget(self.PyContUp)
        self.PyContDown = QtWidgets.QToolButton(AttoPos)
        self.PyContDown.setMinimumSize(QtCore.QSize(75, 70))
        self.PyContDown.setMaximumSize(QtCore.QSize(75, 70))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ArrowDown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PyContDown.setIcon(icon2)
        self.PyContDown.setIconSize(QtCore.QSize(35, 35))
        self.PyContDown.setObjectName("PyContDown")
        self.verticalLayout_6.addWidget(self.PyContDown)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 6, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PzStepUp = QtWidgets.QToolButton(AttoPos)
        self.PzStepUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PzStepUp.setMaximumSize(QtCore.QSize(75, 70))
        self.PzStepUp.setIcon(icon1)
        self.PzStepUp.setIconSize(QtCore.QSize(35, 35))
        self.PzStepUp.setObjectName("PzStepUp")
        self.verticalLayout_4.addWidget(self.PzStepUp)
        self.PzStepDown = QtWidgets.QToolButton(AttoPos)
        self.PzStepDown.setMinimumSize(QtCore.QSize(75, 75))
        self.PzStepDown.setMaximumSize(QtCore.QSize(75, 75))
        self.PzStepDown.setIcon(icon2)
        self.PzStepDown.setIconSize(QtCore.QSize(35, 35))
        self.PzStepDown.setObjectName("PzStepDown")
        self.verticalLayout_4.addWidget(self.PzStepDown)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 5, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_15 = QtWidgets.QLabel(AttoPos)
        self.label_15.setMinimumSize(QtCore.QSize(16, 150))
        self.label_15.setMaximumSize(QtCore.QSize(50, 150))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.PstepMultiplier = QtWidgets.QSpinBox(AttoPos)
        self.PstepMultiplier.setMinimumSize(QtCore.QSize(50, 39))
        self.PstepMultiplier.setMaximumSize(QtCore.QSize(50, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PstepMultiplier.setFont(font)
        self.PstepMultiplier.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PstepMultiplier.setMinimum(1)
        self.PstepMultiplier.setMaximum(99)
        self.PstepMultiplier.setProperty("value", 1)
        self.PstepMultiplier.setObjectName("PstepMultiplier")
        self.horizontalLayout.addWidget(self.PstepMultiplier)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_11 = QtWidgets.QLabel(AttoPos)
        self.label_11.setMinimumSize(QtCore.QSize(40, 150))
        self.label_11.setMaximumSize(QtCore.QSize(40, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLineWidth(1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PxContUp = QtWidgets.QToolButton(AttoPos)
        self.PxContUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PxContUp.setMaximumSize(QtCore.QSize(75, 70))
        self.PxContUp.setIcon(icon1)
        self.PxContUp.setIconSize(QtCore.QSize(35, 35))
        self.PxContUp.setObjectName("PxContUp")
        self.verticalLayout_5.addWidget(self.PxContUp)
        self.PxContDown = QtWidgets.QToolButton(AttoPos)
        self.PxContDown.setMinimumSize(QtCore.QSize(75, 70))
        self.PxContDown.setMaximumSize(QtCore.QSize(75, 70))
        self.PxContDown.setIcon(icon2)
        self.PxContDown.setIconSize(QtCore.QSize(35, 35))
        self.PxContDown.setObjectName("PxContDown")
        self.verticalLayout_5.addWidget(self.PxContDown)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 6, 2, 1, 1)
        self.PyFreq = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PyFreq.setMinimumSize(QtCore.QSize(105, 39))
        self.PyFreq.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PyFreq.setFont(font)
        self.PyFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PyFreq.setDecimals(0)
        self.PyFreq.setMinimum(1.0)
        self.PyFreq.setMaximum(600.0)
        self.PyFreq.setProperty("value", 100.0)
        self.PyFreq.setObjectName("PyFreq")
        self.gridLayout_3.addWidget(self.PyFreq, 3, 3, 1, 1)
        self.PzFreq = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PzFreq.setMinimumSize(QtCore.QSize(105, 39))
        self.PzFreq.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PzFreq.setFont(font)
        self.PzFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PzFreq.setDecimals(0)
        self.PzFreq.setMinimum(1.0)
        self.PzFreq.setMaximum(600.0)
        self.PzFreq.setProperty("value", 100.0)
        self.PzFreq.setObjectName("PzFreq")
        self.gridLayout_3.addWidget(self.PzFreq, 3, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PxStepUp = QtWidgets.QToolButton(AttoPos)
        self.PxStepUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PxStepUp.setMaximumSize(QtCore.QSize(75, 70))
        self.PxStepUp.setIcon(icon1)
        self.PxStepUp.setIconSize(QtCore.QSize(35, 35))
        self.PxStepUp.setObjectName("PxStepUp")
        self.verticalLayout_2.addWidget(self.PxStepUp)
        self.PxStepDown = QtWidgets.QToolButton(AttoPos)
        self.PxStepDown.setMinimumSize(QtCore.QSize(75, 70))
        self.PxStepDown.setMaximumSize(QtCore.QSize(75, 70))
        self.PxStepDown.setIcon(icon2)
        self.PxStepDown.setIconSize(QtCore.QSize(35, 35))
        self.PxStepDown.setArrowType(QtCore.Qt.NoArrow)
        self.PxStepDown.setObjectName("PxStepDown")
        self.verticalLayout_2.addWidget(self.PxStepDown)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 5, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PzContUp = QtWidgets.QToolButton(AttoPos)
        self.PzContUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PzContUp.setMaximumSize(QtCore.QSize(75, 70))
        self.PzContUp.setIcon(icon1)
        self.PzContUp.setIconSize(QtCore.QSize(35, 35))
        self.PzContUp.setObjectName("PzContUp")
        self.verticalLayout_7.addWidget(self.PzContUp)
        self.PzContDown = QtWidgets.QToolButton(AttoPos)
        self.PzContDown.setMinimumSize(QtCore.QSize(75, 70))
        self.PzContDown.setMaximumSize(QtCore.QSize(75, 70))
        self.PzContDown.setIcon(icon2)
        self.PzContDown.setIconSize(QtCore.QSize(35, 35))
        self.PzContDown.setObjectName("PzContDown")
        self.verticalLayout_7.addWidget(self.PzContDown)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 6, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PyStepUp = QtWidgets.QToolButton(AttoPos)
        self.PyStepUp.setMinimumSize(QtCore.QSize(75, 70))
        self.PyStepUp.setMaximumSize(QtCore.QSize(75, 70))
        self.PyStepUp.setIcon(icon1)
        self.PyStepUp.setIconSize(QtCore.QSize(35, 35))
        self.PyStepUp.setObjectName("PyStepUp")
        self.verticalLayout_3.addWidget(self.PyStepUp)
        self.PyStepDown = QtWidgets.QToolButton(AttoPos)
        self.PyStepDown.setMinimumSize(QtCore.QSize(75, 70))
        self.PyStepDown.setMaximumSize(QtCore.QSize(75, 70))
        self.PyStepDown.setIcon(icon2)
        self.PyStepDown.setIconSize(QtCore.QSize(35, 35))
        self.PyStepDown.setObjectName("PyStepDown")
        self.verticalLayout_3.addWidget(self.PyStepDown)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 5, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(AttoPos)
        self.label_18.setMinimumSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(AttoPos)
        self.label_16.setMinimumSize(QtCore.QSize(106, 39))
        self.label_16.setMaximumSize(QtCore.QSize(2000, 39))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(AttoPos)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 5, 1, 1)
        self.PzOffset = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PzOffset.setEnabled(False)
        self.PzOffset.setMinimumSize(QtCore.QSize(105, 39))
        self.PzOffset.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PzOffset.setFont(font)
        self.PzOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PzOffset.setDecimals(1)
        self.PzOffset.setMaximum(150.0)
        self.PzOffset.setObjectName("PzOffset")
        self.gridLayout_3.addWidget(self.PzOffset, 4, 4, 1, 1)
        self.PyOffset = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PyOffset.setEnabled(False)
        self.PyOffset.setMinimumSize(QtCore.QSize(105, 39))
        self.PyOffset.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PyOffset.setFont(font)
        self.PyOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PyOffset.setDecimals(1)
        self.PyOffset.setMaximum(150.0)
        self.PyOffset.setObjectName("PyOffset")
        self.gridLayout_3.addWidget(self.PyOffset, 4, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_12 = QtWidgets.QLabel(AttoPos)
        self.label_12.setMinimumSize(QtCore.QSize(40, 150))
        self.label_12.setMaximumSize(QtCore.QSize(40, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.PxOffset = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PxOffset.setEnabled(False)
        self.PxOffset.setMinimumSize(QtCore.QSize(105, 39))
        self.PxOffset.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PxOffset.setFont(font)
        self.PxOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PxOffset.setDecimals(1)
        self.PxOffset.setMaximum(150.0)
        self.PxOffset.setObjectName("PxOffset")
        self.gridLayout_3.addWidget(self.PxOffset, 4, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(AttoPos)
        self.label_8.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.PxGnd = QtWidgets.QCheckBox(AttoPos)
        self.PxGnd.setObjectName("PxGnd")
        self.horizontalLayout_5.addWidget(self.PxGnd)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(AttoPos)
        self.label_13.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.PyGnd = QtWidgets.QCheckBox(AttoPos)
        self.PyGnd.setObjectName("PyGnd")
        self.horizontalLayout_6.addWidget(self.PyGnd)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 3, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(AttoPos)
        self.label_14.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.PzGnd = QtWidgets.QCheckBox(AttoPos)
        self.PzGnd.setObjectName("PzGnd")
        self.horizontalLayout_7.addWidget(self.PzGnd)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 4, 1, 1)
        self.PyAmp = QtWidgets.QDoubleSpinBox(AttoPos)
        self.PyAmp.setMinimumSize(QtCore.QSize(105, 39))
        self.PyAmp.setMaximumSize(QtCore.QSize(105, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PyAmp.setFont(font)
        self.PyAmp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PyAmp.setDecimals(1)
        self.PyAmp.setMinimum(0.1)
        self.PyAmp.setMaximum(60.0)
        self.PyAmp.setSingleStep(0.1)
        self.PyAmp.setProperty("value", 40.0)
        self.PyAmp.setObjectName("PyAmp")
        self.gridLayout_3.addWidget(self.PyAmp, 2, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 7, 1)
        self.arrowKeyControl = QtWidgets.QToolButton(AttoPos)
        self.arrowKeyControl.setMinimumSize(QtCore.QSize(150, 350))
        self.arrowKeyControl.setMaximumSize(QtCore.QSize(150, 350))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.arrowKeyControl.setFont(font)
        self.arrowKeyControl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowKeyControl.setStyleSheet("background-color: rgb(38, 234, 68);")
        self.arrowKeyControl.setCheckable(True)
        self.arrowKeyControl.setObjectName("arrowKeyControl")
        self.gridLayout.addWidget(self.arrowKeyControl, 0, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        self.contXled = QtWidgets.QLabel(AttoPos)
        self.contXled.setMinimumSize(QtCore.QSize(150, 65))
        self.contXled.setMaximumSize(QtCore.QSize(150, 65))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.contXled.setFont(font)
        self.contXled.setStyleSheet("background-color: rgb(0, 115, 255);\n"
"color: rgb(255, 255, 255);")
        self.contXled.setAlignment(QtCore.Qt.AlignCenter)
        self.contXled.setObjectName("contXled")
        self.gridLayout.addWidget(self.contXled, 2, 1, 1, 3)
        self.contZled = QtWidgets.QLabel(AttoPos)
        self.contZled.setMinimumSize(QtCore.QSize(150, 65))
        self.contZled.setMaximumSize(QtCore.QSize(150, 65))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.contZled.setFont(font)
        self.contZled.setStyleSheet("background-color: rgb(0, 115, 255);\n"
"color: rgb(255, 255, 255);")
        self.contZled.setAlignment(QtCore.Qt.AlignCenter)
        self.contZled.setObjectName("contZled")
        self.gridLayout.addWidget(self.contZled, 4, 1, 1, 1)

        self.retranslateUi(AttoPos)
        QtCore.QMetaObject.connectSlotsByName(AttoPos)
        AttoPos.setTabOrder(self.PxGnd, self.PyGnd)
        AttoPos.setTabOrder(self.PyGnd, self.PzGnd)
        AttoPos.setTabOrder(self.PzGnd, self.SxGnd)
        AttoPos.setTabOrder(self.SxGnd, self.SyGnd)
        AttoPos.setTabOrder(self.SyGnd, self.SzGnd)
        AttoPos.setTabOrder(self.SzGnd, self.PxAmp)
        AttoPos.setTabOrder(self.PxAmp, self.PyAmp)
        AttoPos.setTabOrder(self.PyAmp, self.PzAmp)
        AttoPos.setTabOrder(self.PzAmp, self.PxFreq)
        AttoPos.setTabOrder(self.PxFreq, self.PyFreq)
        AttoPos.setTabOrder(self.PyFreq, self.PzFreq)
        AttoPos.setTabOrder(self.PzFreq, self.PxOffset)
        AttoPos.setTabOrder(self.PxOffset, self.PyOffset)
        AttoPos.setTabOrder(self.PyOffset, self.PzOffset)
        AttoPos.setTabOrder(self.PzOffset, self.PstepMultiplier)
        AttoPos.setTabOrder(self.PstepMultiplier, self.PxStepUp)
        AttoPos.setTabOrder(self.PxStepUp, self.PxStepDown)
        AttoPos.setTabOrder(self.PxStepDown, self.PyStepUp)
        AttoPos.setTabOrder(self.PyStepUp, self.PyStepDown)
        AttoPos.setTabOrder(self.PyStepDown, self.PzStepUp)
        AttoPos.setTabOrder(self.PzStepUp, self.PzStepDown)
        AttoPos.setTabOrder(self.PzStepDown, self.PxContUp)
        AttoPos.setTabOrder(self.PxContUp, self.PxContDown)
        AttoPos.setTabOrder(self.PxContDown, self.PyContUp)
        AttoPos.setTabOrder(self.PyContUp, self.PyContDown)
        AttoPos.setTabOrder(self.PyContDown, self.PzContUp)
        AttoPos.setTabOrder(self.PzContUp, self.PzContDown)
        AttoPos.setTabOrder(self.PzContDown, self.SxDeactivate)
        AttoPos.setTabOrder(self.SxDeactivate, self.SxPos)
        AttoPos.setTabOrder(self.SxPos, self.SyDeactivate)
        AttoPos.setTabOrder(self.SyDeactivate, self.SyPos)
        AttoPos.setTabOrder(self.SyPos, self.SzDeactivate)
        AttoPos.setTabOrder(self.SzDeactivate, self.SzPos)
        AttoPos.setTabOrder(self.SzPos, self.SstepSize)
        AttoPos.setTabOrder(self.SstepSize, self.arrowKeyControl)

    def retranslateUi(self, AttoPos):
        _translate = QtCore.QCoreApplication.translate
        AttoPos.setWindowTitle(_translate("AttoPos", "Attocube Positioners and Scanners Control"))
        self.contYled.setText(_translate("AttoPos", "CONT Y"))
        self.label2_4.setText(_translate("AttoPos", "Sx"))
        self.SxGnd.setText(_translate("AttoPos", "GND"))
        self.SxDeactivate.setText(_translate("AttoPos", "Deactivate"))
        self.label2_5.setText(_translate("AttoPos", "Sy"))
        self.SyGnd.setText(_translate("AttoPos", "GND"))
        self.SyDeactivate.setText(_translate("AttoPos", "Deactivate"))
        self.label_6.setText(_translate("AttoPos", "Sz"))
        self.SzGnd.setText(_translate("AttoPos", "GND"))
        self.SzDeactivate.setText(_translate("AttoPos", "Deactivate"))
        self.label_3.setText(_translate("AttoPos", "Step:"))
        self.label_4.setText(_translate("AttoPos", "V"))
        self.label_20.setText(_translate("AttoPos", "Keyboard navigation:"))
        self.label_22.setText(_translate("AttoPos", "Sx up/down: arrows left/right\n"
"Sy up/down: arrows up/down\n"
"Sz up: page up/page down\n"
"Px up/down: 6/4\n"
"Py up/down: 8/5"))
        self.label_23.setText(_translate("AttoPos", "Pz up: Minus (numpad)\n"
"Pz down: Plus (numpad).\n"
"Positioners: step mode default.\n"
"Continuous: Ctrl+Key.\n"
"Cont. locked: Ctrl+Alt+Key."))
        self.label.setText(_translate("AttoPos", "STOP ALL: 0 (zero)."))
        self.label_2.setText(_translate("AttoPos", "Scanners"))
        self.label_5.setText(_translate("AttoPos", "Positioners"))
        self.label_19.setText(_translate("AttoPos", "V"))
        self.label_9.setText(_translate("AttoPos", "Frequency:"))
        self.label_10.setText(_translate("AttoPos", "Amplitude:"))
        self.PyContUp.setText(_translate("AttoPos", "..."))
        self.PyContDown.setText(_translate("AttoPos", "..."))
        self.PzStepUp.setText(_translate("AttoPos", "..."))
        self.PzStepDown.setText(_translate("AttoPos", "..."))
        self.label_15.setText(_translate("AttoPos", "×"))
        self.label_11.setText(_translate("AttoPos", "S\n"
"T\n"
"E\n"
"P"))
        self.PxContUp.setText(_translate("AttoPos", "..."))
        self.PxContDown.setText(_translate("AttoPos", "..."))
        self.PxStepUp.setText(_translate("AttoPos", "..."))
        self.PxStepDown.setText(_translate("AttoPos", "..."))
        self.PzContUp.setText(_translate("AttoPos", "..."))
        self.PzContDown.setText(_translate("AttoPos", "..."))
        self.PyStepUp.setText(_translate("AttoPos", "..."))
        self.PyStepDown.setText(_translate("AttoPos", "..."))
        self.label_18.setText(_translate("AttoPos", "Hz"))
        self.label_16.setText(_translate("AttoPos", "Offset:"))
        self.label_17.setText(_translate("AttoPos", "V"))
        self.label_12.setText(_translate("AttoPos", "C\n"
"O\n"
"N\n"
"T"))
        self.label_8.setText(_translate("AttoPos", "Px"))
        self.PxGnd.setText(_translate("AttoPos", "GND"))
        self.label_13.setText(_translate("AttoPos", "Py"))
        self.PyGnd.setText(_translate("AttoPos", "GND"))
        self.label_14.setText(_translate("AttoPos", "Pz"))
        self.PzGnd.setText(_translate("AttoPos", "GND"))
        self.arrowKeyControl.setToolTip(_translate("AttoPos", "Shortcut: Ctrl+Space"))
        self.arrowKeyControl.setText(_translate("AttoPos", "KEYBOARD\n"
"NAVIGATION\n"
"CONTROL"))
        self.contXled.setText(_translate("AttoPos", "CONT X"))
        self.contZled.setText(_translate("AttoPos", "CONT Z"))

