# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multimeterOscillo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_multimeterOscillo(object):
    def setupUi(self, keithleyOscillo):
        keithleyOscillo.setObjectName("keithleyOscillo")
        keithleyOscillo.resize(978, 725)
        self.verticalLayout = QtWidgets.QVBoxLayout(keithleyOscillo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(keithleyOscillo)
        self.label_5.setStyleSheet("font: 40pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 12, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(keithleyOscillo)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.min = QtWidgets.QDoubleSpinBox(keithleyOscillo)
        self.min.setDecimals(3)
        self.min.setMinimum(-100.0)
        self.min.setMaximum(100.0)
        self.min.setObjectName("min")
        self.horizontalLayout.addWidget(self.min)
        self.label_2 = QtWidgets.QLabel(keithleyOscillo)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.max = QtWidgets.QDoubleSpinBox(keithleyOscillo)
        self.max.setDecimals(3)
        self.max.setMinimum(-100.0)
        self.max.setMaximum(100.0)
        self.max.setProperty("value", 5.0)
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.rangeAutoscaleBox = QtWidgets.QCheckBox(keithleyOscillo)
        self.rangeAutoscaleBox.setObjectName("rangeAutoscaleBox")
        self.horizontalLayout.addWidget(self.rangeAutoscaleBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(keithleyOscillo)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.scalingFactor = QtWidgets.QDoubleSpinBox(keithleyOscillo)
        self.scalingFactor.setMinimumSize(QtCore.QSize(100, 20))
        self.scalingFactor.setMaximumSize(QtCore.QSize(100, 20))
        self.scalingFactor.setDecimals(6)
        self.scalingFactor.setMaximum(999999999.999999)
        self.scalingFactor.setProperty("value", 1.0)
        self.scalingFactor.setObjectName("scalingFactor")
        self.horizontalLayout_5.addWidget(self.scalingFactor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(keithleyOscillo)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.tStep = QtWidgets.QDoubleSpinBox(keithleyOscillo)
        self.tStep.setDecimals(3)
        self.tStep.setMinimum(0.01)
        self.tStep.setSingleStep(0.01)
        self.tStep.setProperty("value", 0.02)
        self.tStep.setObjectName("tStep")
        self.horizontalLayout_2.addWidget(self.tStep)
        self.label_3 = QtWidgets.QLabel(keithleyOscillo)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.tWindow = QtWidgets.QDoubleSpinBox(keithleyOscillo)
        self.tWindow.setDecimals(3)
        self.tWindow.setMinimum(0.001)
        self.tWindow.setProperty("value", 10.0)
        self.tWindow.setObjectName("tWindow")
        self.horizontalLayout_2.addWidget(self.tWindow)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 7, 1, 1)
        self.nbReading = QtWidgets.QLCDNumber(keithleyOscillo)
        self.nbReading.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.nbReading.setFont(font)
        self.nbReading.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nbReading.setAutoFillBackground(True)
        self.nbReading.setSmallDecimalPoint(False)
        self.nbReading.setNumDigits(8)
        self.nbReading.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbReading.setProperty("value", 11.0)
        self.nbReading.setProperty("intValue", 11)
        self.nbReading.setObjectName("nbReading")
        self.gridLayout.addWidget(self.nbReading, 0, 5, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(keithleyOscillo)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.nbMinEnabled = QtWidgets.QCheckBox(keithleyOscillo)
        self.nbMinEnabled.setText("")
        self.nbMinEnabled.setChecked(True)
        self.nbMinEnabled.setObjectName("nbMinEnabled")
        self.horizontalLayout_3.addWidget(self.nbMinEnabled)
        self.nbMinReadingReset = QtWidgets.QPushButton(keithleyOscillo)
        self.nbMinReadingReset.setMinimumSize(QtCore.QSize(60, 30))
        self.nbMinReadingReset.setMaximumSize(QtCore.QSize(60, 30))
        self.nbMinReadingReset.setObjectName("nbMinReadingReset")
        self.horizontalLayout_3.addWidget(self.nbMinReadingReset)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.nbMinReading = QtWidgets.QLCDNumber(keithleyOscillo)
        self.nbMinReading.setMinimumSize(QtCore.QSize(150, 0))
        self.nbMinReading.setSmallDecimalPoint(False)
        self.nbMinReading.setNumDigits(8)
        self.nbMinReading.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbMinReading.setProperty("value", 0.0)
        self.nbMinReading.setObjectName("nbMinReading")
        self.verticalLayout_5.addWidget(self.nbMinReading)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 9, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(keithleyOscillo)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.nbMaxEnabled = QtWidgets.QCheckBox(keithleyOscillo)
        self.nbMaxEnabled.setText("")
        self.nbMaxEnabled.setChecked(True)
        self.nbMaxEnabled.setObjectName("nbMaxEnabled")
        self.horizontalLayout_6.addWidget(self.nbMaxEnabled)
        self.nbMaxReadingReset = QtWidgets.QPushButton(keithleyOscillo)
        self.nbMaxReadingReset.setMinimumSize(QtCore.QSize(60, 30))
        self.nbMaxReadingReset.setMaximumSize(QtCore.QSize(60, 30))
        self.nbMaxReadingReset.setStyleSheet("")
        self.nbMaxReadingReset.setObjectName("nbMaxReadingReset")
        self.horizontalLayout_6.addWidget(self.nbMaxReadingReset)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.nbMaxReading = QtWidgets.QLCDNumber(keithleyOscillo)
        self.nbMaxReading.setMinimumSize(QtCore.QSize(150, 0))
        self.nbMaxReading.setSmallDecimalPoint(False)
        self.nbMaxReading.setNumDigits(8)
        self.nbMaxReading.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbMaxReading.setProperty("value", 0.0)
        self.nbMaxReading.setObjectName("nbMaxReading")
        self.verticalLayout_4.addWidget(self.nbMaxReading)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 10, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.graphicsView = PlotWidget(keithleyOscillo)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(keithleyOscillo)
        QtCore.QMetaObject.connectSlotsByName(keithleyOscillo)
        keithleyOscillo.setTabOrder(self.min, self.max)
        keithleyOscillo.setTabOrder(self.max, self.rangeAutoscaleBox)
        keithleyOscillo.setTabOrder(self.rangeAutoscaleBox, self.scalingFactor)
        keithleyOscillo.setTabOrder(self.scalingFactor, self.tStep)
        keithleyOscillo.setTabOrder(self.tStep, self.tWindow)
        keithleyOscillo.setTabOrder(self.tWindow, self.nbMaxEnabled)
        keithleyOscillo.setTabOrder(self.nbMaxEnabled, self.nbMaxReadingReset)
        keithleyOscillo.setTabOrder(self.nbMaxReadingReset, self.nbMinEnabled)
        keithleyOscillo.setTabOrder(self.nbMinEnabled, self.nbMinReadingReset)
        keithleyOscillo.setTabOrder(self.nbMinReadingReset, self.graphicsView)

    def retranslateUi(self, keithleyOscillo):
        _translate = QtCore.QCoreApplication.translate
        keithleyOscillo.setWindowTitle(_translate("keithleyOscillo", "Keithley Voltmeter"))
        self.label_5.setText(_translate("keithleyOscillo", "V"))
        self.label.setText(_translate("keithleyOscillo", "Min (V)"))
        self.label_2.setText(_translate("keithleyOscillo", "Max (V)"))
        self.rangeAutoscaleBox.setText(_translate("keithleyOscillo", "Auto"))
        self.label_6.setText(_translate("keithleyOscillo", "Factor (display = V * factor)"))
        self.label_4.setText(_translate("keithleyOscillo", "Time step (s)"))
        self.label_3.setText(_translate("keithleyOscillo", "Time window (s)"))
        self.label_8.setText(_translate("keithleyOscillo", "MIN"))
        self.nbMinReadingReset.setText(_translate("keithleyOscillo", "RESET"))
        self.label_7.setText(_translate("keithleyOscillo", "MAX"))
        self.nbMaxReadingReset.setText(_translate("keithleyOscillo", "RESET"))

from pyqtgraph import PlotWidget
