# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cristian\Research\QPL-code\measurements\scripts\bay5\Galvo_GUI\scan_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 406)
        self.pushButton_Start = QtWidgets.QPushButton(Form)
        self.pushButton_Start.setGeometry(QtCore.QRect(480, 270, 93, 28))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(Form)
        self.pushButton_Stop.setGeometry(QtCore.QRect(480, 300, 93, 28))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 451, 381))
        self.graphicsView.setObjectName("graphicsView")
        self.cb_detector = QtWidgets.QComboBox(Form)
        self.cb_detector.setGeometry(QtCore.QRect(610, 300, 101, 21))
        self.cb_detector.setObjectName("cb_detector")
        self.label_Detectors = QtWidgets.QLabel(Form)
        self.label_Detectors.setGeometry(QtCore.QRect(610, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_Detectors.setFont(font)
        self.label_Detectors.setObjectName("label_Detectors")
        self.dsB_min1 = QtWidgets.QDoubleSpinBox(Form)
        self.dsB_min1.setGeometry(QtCore.QRect(530, 20, 62, 22))
        self.dsB_min1.setObjectName("dsB_min1")
        self.dsB_min2 = QtWidgets.QDoubleSpinBox(Form)
        self.dsB_min2.setGeometry(QtCore.QRect(530, 50, 62, 22))
        self.dsB_min2.setObjectName("dsB_min2")
        self.dsB_max1 = QtWidgets.QDoubleSpinBox(Form)
        self.dsB_max1.setGeometry(QtCore.QRect(600, 20, 62, 22))
        self.dsB_max1.setObjectName("dsB_max1")
        self.dsb_max2 = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_max2.setGeometry(QtCore.QRect(600, 50, 62, 22))
        self.dsb_max2.setObjectName("dsb_max2")
        self.dsB_steps1 = QtWidgets.QDoubleSpinBox(Form)
        self.dsB_steps1.setGeometry(QtCore.QRect(670, 20, 62, 22))
        self.dsB_steps1.setObjectName("dsB_steps1")
        self.dsb_steps2 = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_steps2.setGeometry(QtCore.QRect(670, 50, 62, 22))
        self.dsb_steps2.setObjectName("dsb_steps2")
        self.pushButton_Save = QtWidgets.QPushButton(Form)
        self.pushButton_Save.setGeometry(QtCore.QRect(480, 360, 93, 28))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_Resume = QtWidgets.QPushButton(Form)
        self.pushButton_Resume.setGeometry(QtCore.QRect(480, 330, 93, 28))
        self.pushButton_Resume.setObjectName("pushButton_Resume")
        self.dsb_fixed_pos = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_fixed_pos.setGeometry(QtCore.QRect(530, 80, 62, 22))
        self.dsb_fixed_pos.setObjectName("dsb_fixed_pos")
        self.cb_scan1 = QtWidgets.QComboBox(Form)
        self.cb_scan1.setGeometry(QtCore.QRect(480, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_scan1.setFont(font)
        self.cb_scan1.setObjectName("cb_scan1")
        self.cb_scan1.addItem("")
        self.cb_scan1.addItem("")
        self.cb_scan1.addItem("")
        self.cb_scan2 = QtWidgets.QComboBox(Form)
        self.cb_scan2.setGeometry(QtCore.QRect(480, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_scan2.setFont(font)
        self.cb_scan2.setObjectName("cb_scan2")
        self.cb_scan2.addItem("")
        self.cb_scan2.addItem("")
        self.cb_scan2.addItem("")
        self.cb_fixed = QtWidgets.QComboBox(Form)
        self.cb_fixed.setGeometry(QtCore.QRect(480, 80, 41, 21))
        self.cb_fixed.setObjectName("cb_fixed")
        self.cb_fixed.addItem("")
        self.cb_fixed.addItem("")
        self.cb_fixed.addItem("")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(470, 10, 271, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_scan = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_scan.setContentsMargins(0, 0, 0, 0)
        self.formLayout_scan.setObjectName("formLayout_scan")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(470, 260, 271, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_buttons = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_buttons.setContentsMargins(0, 0, 0, 0)
        self.formLayout_buttons.setObjectName("formLayout_buttons")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_Start.setText(_translate("Form", "Start"))
        self.pushButton_Stop.setText(_translate("Form", "Stop"))
        self.label_Detectors.setText(_translate("Form", "Detector"))
        self.pushButton_Save.setText(_translate("Form", "Save"))
        self.pushButton_Resume.setText(_translate("Form", "Resume"))
        self.cb_scan1.setItemText(0, _translate("Form", "x"))
        self.cb_scan1.setItemText(1, _translate("Form", "y"))
        self.cb_scan1.setItemText(2, _translate("Form", "z"))
        self.cb_scan2.setCurrentText(_translate("Form", "y"))
        self.cb_scan2.setItemText(0, _translate("Form", "x"))
        self.cb_scan2.setItemText(1, _translate("Form", "y"))
        self.cb_scan2.setItemText(2, _translate("Form", "z"))
        self.cb_fixed.setItemText(0, _translate("Form", "x"))
        self.cb_fixed.setItemText(1, _translate("Form", "y"))
        self.cb_fixed.setItemText(2, _translate("Form", "z"))

