# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QPLser_view2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(1155, 750)
        self.button_save = QtWidgets.QPushButton(Panel)
        self.button_save.setGeometry(QtCore.QRect(940, 672, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setObjectName("button_save")
        self.plot = QtWidgets.QGraphicsView(Panel)
        self.plot.setGeometry(QtCore.QRect(10, 10, 1131, 561))
        self.plot.setObjectName("plot")
        self.lineEdit_fileName = QtWidgets.QLineEdit(Panel)
        self.lineEdit_fileName.setGeometry(QtCore.QRect(940, 710, 181, 20))
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.label_fileTag = QtWidgets.QLabel(Panel)
        self.label_fileTag.setGeometry(QtCore.QRect(880, 710, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_fileTag.setFont(font)
        self.label_fileTag.setObjectName("label_fileTag")
        self.sb_nr_steps_finelaser = QtWidgets.QSpinBox(Panel)
        self.sb_nr_steps_finelaser.setGeometry(QtCore.QRect(100, 650, 81, 31))
        self.sb_nr_steps_finelaser.setObjectName("sb_nr_steps_finelaser")
        self.label_maxV__finelaser = QtWidgets.QLabel(Panel)
        self.label_maxV__finelaser.setGeometry(QtCore.QRect(540, 680, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_maxV__finelaser.setFont(font)
        self.label_maxV__finelaser.setObjectName("label_maxV__finelaser")
        self.label_nr_steps_finelaser = QtWidgets.QLabel(Panel)
        self.label_nr_steps_finelaser.setGeometry(QtCore.QRect(30, 650, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_nr_steps_finelaser.setFont(font)
        self.label_nr_steps_finelaser.setObjectName("label_nr_steps_finelaser")
        self.dsb_maxV_finelaser = QtWidgets.QDoubleSpinBox(Panel)
        self.dsb_maxV_finelaser.setGeometry(QtCore.QRect(541, 711, 81, 21))
        self.dsb_maxV_finelaser.setObjectName("dsb_maxV_finelaser")
        self.horizontalScrollBar = QtWidgets.QScrollBar(Panel)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 580, 1131, 21))
        self.horizontalScrollBar.setPageStep(50)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.cb_autostop_2 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_2.setGeometry(QtCore.QRect(30, 687, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_2.setFont(font)
        self.cb_autostop_2.setObjectName("cb_autostop_2")
        self.cb_autostop_3 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_3.setGeometry(QtCore.QRect(30, 710, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_3.setFont(font)
        self.cb_autostop_3.setObjectName("cb_autostop_3")
        self.cb_autostop_4 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_4.setGeometry(QtCore.QRect(90, 710, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_4.setFont(font)
        self.cb_autostop_4.setObjectName("cb_autostop_4")
        self.cb_autostop_5 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_5.setGeometry(QtCore.QRect(90, 690, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_5.setFont(font)
        self.cb_autostop_5.setObjectName("cb_autostop_5")
        self.cb_autostop_6 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_6.setGeometry(QtCore.QRect(150, 710, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_6.setFont(font)
        self.cb_autostop_6.setObjectName("cb_autostop_6")
        self.cb_autostop_7 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_7.setGeometry(QtCore.QRect(150, 690, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_7.setFont(font)
        self.cb_autostop_7.setObjectName("cb_autostop_7")
        self.cb_autostop_8 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_8.setGeometry(QtCore.QRect(210, 710, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_8.setFont(font)
        self.cb_autostop_8.setObjectName("cb_autostop_8")
        self.cb_autostop_9 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_9.setGeometry(QtCore.QRect(210, 690, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_9.setFont(font)
        self.cb_autostop_9.setObjectName("cb_autostop_9")
        self.cb_autostop_10 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_10.setGeometry(QtCore.QRect(300, 710, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_10.setFont(font)
        self.cb_autostop_10.setObjectName("cb_autostop_10")
        self.cb_autostop_11 = QtWidgets.QCheckBox(Panel)
        self.cb_autostop_11.setGeometry(QtCore.QRect(300, 690, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_autostop_11.setFont(font)
        self.cb_autostop_11.setObjectName("cb_autostop_11")
        self.comboBox = QtWidgets.QComboBox(Panel)
        self.comboBox.setGeometry(QtCore.QRect(630, 710, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_nr_steps_finelaser_2 = QtWidgets.QLabel(Panel)
        self.label_nr_steps_finelaser_2.setGeometry(QtCore.QRect(30, 610, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_nr_steps_finelaser_2.setFont(font)
        self.label_nr_steps_finelaser_2.setObjectName("label_nr_steps_finelaser_2")

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Panel"))
        self.button_save.setText(_translate("Panel", "SAVE view"))
        self.label_fileTag.setText(_translate("Panel", "file tag:"))
        self.label_maxV__finelaser.setText(_translate("Panel", "View time interval"))
        self.label_nr_steps_finelaser.setText(_translate("Panel", "Rep nr"))
        self.cb_autostop_2.setText(_translate("Panel", "D0"))
        self.cb_autostop_3.setText(_translate("Panel", "D1"))
        self.cb_autostop_4.setText(_translate("Panel", "D3"))
        self.cb_autostop_5.setText(_translate("Panel", "D2"))
        self.cb_autostop_6.setText(_translate("Panel", "D5"))
        self.cb_autostop_7.setText(_translate("Panel", "D4"))
        self.cb_autostop_8.setText(_translate("Panel", "D7"))
        self.cb_autostop_9.setText(_translate("Panel", "D6"))
        self.cb_autostop_10.setText(_translate("Panel", "A1"))
        self.cb_autostop_11.setText(_translate("Panel", "A0"))
        self.label_nr_steps_finelaser_2.setText(_translate("Panel", "QPLser - Stream Viewer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Panel = QtWidgets.QWidget()
    ui = Ui_Panel()
    ui.setupUi(Panel)
    Panel.show()
    sys.exit(app.exec_())

