# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optimizer_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1003, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 11, 892, 462))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Optimizer_title = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Optimizer_title.setFont(font)
        self.Optimizer_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Optimizer_title.setObjectName("Optimizer_title")
        self.verticalLayout_5.addWidget(self.Optimizer_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Xtitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.Xtitle.setFont(font)
        self.Xtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Xtitle.setObjectName("Xtitle")
        self.verticalLayout.addWidget(self.Xtitle)
        self.cB_X = QtWidgets.QComboBox(self.widget)
        self.cB_X.setObjectName("cB_X")
        self.verticalLayout.addWidget(self.cB_X)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_X0 = QtWidgets.QLabel(self.widget)
        self.label_X0.setObjectName("label_X0")
        self.gridLayout.addWidget(self.label_X0, 0, 0, 1, 1)
        self.dsB_X0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_X0.setObjectName("dsB_X0")
        self.gridLayout.addWidget(self.dsB_X0, 0, 1, 1, 1)
        self.label_Xrange = QtWidgets.QLabel(self.widget)
        self.label_Xrange.setObjectName("label_Xrange")
        self.gridLayout.addWidget(self.label_Xrange, 1, 0, 1, 1)
        self.dsB_Xrange = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_Xrange.setObjectName("dsB_Xrange")
        self.gridLayout.addWidget(self.dsB_Xrange, 1, 1, 1, 1)
        self.label_Xsteps = QtWidgets.QLabel(self.widget)
        self.label_Xsteps.setObjectName("label_Xsteps")
        self.gridLayout.addWidget(self.label_Xsteps, 2, 0, 1, 1)
        self.sB_Xsteps = QtWidgets.QSpinBox(self.widget)
        self.sB_Xsteps.setMinimum(1)
        self.sB_Xsteps.setObjectName("sB_Xsteps")
        self.gridLayout.addWidget(self.sB_Xsteps, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.viewX = QtWidgets.QGraphicsView(self.widget)
        self.viewX.setObjectName("viewX")
        self.verticalLayout_2.addWidget(self.viewX)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Ytitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.Ytitle.setFont(font)
        self.Ytitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Ytitle.setObjectName("Ytitle")
        self.verticalLayout_3.addWidget(self.Ytitle)
        self.cB_Y = QtWidgets.QComboBox(self.widget)
        self.cB_Y.setObjectName("cB_Y")
        self.verticalLayout_3.addWidget(self.cB_Y)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Y0 = QtWidgets.QLabel(self.widget)
        self.label_Y0.setObjectName("label_Y0")
        self.gridLayout_2.addWidget(self.label_Y0, 0, 0, 1, 1)
        self.dsB_Y0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_Y0.setObjectName("dsB_Y0")
        self.gridLayout_2.addWidget(self.dsB_Y0, 0, 1, 1, 1)
        self.label_Yrange = QtWidgets.QLabel(self.widget)
        self.label_Yrange.setObjectName("label_Yrange")
        self.gridLayout_2.addWidget(self.label_Yrange, 1, 0, 1, 1)
        self.dsB_Yrange = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_Yrange.setObjectName("dsB_Yrange")
        self.gridLayout_2.addWidget(self.dsB_Yrange, 1, 1, 1, 1)
        self.label_Ysteps = QtWidgets.QLabel(self.widget)
        self.label_Ysteps.setObjectName("label_Ysteps")
        self.gridLayout_2.addWidget(self.label_Ysteps, 2, 0, 1, 1)
        self.sB_Ysteps = QtWidgets.QSpinBox(self.widget)
        self.sB_Ysteps.setMinimum(1)
        self.sB_Ysteps.setObjectName("sB_Ysteps")
        self.gridLayout_2.addWidget(self.sB_Ysteps, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.viewY = QtWidgets.QGraphicsView(self.widget)
        self.viewY.setObjectName("viewY")
        self.verticalLayout_3.addWidget(self.viewY)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Ztitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.Ztitle.setFont(font)
        self.Ztitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Ztitle.setObjectName("Ztitle")
        self.verticalLayout_4.addWidget(self.Ztitle)
        self.cB_Z = QtWidgets.QComboBox(self.widget)
        self.cB_Z.setObjectName("cB_Z")
        self.verticalLayout_4.addWidget(self.cB_Z)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_Z0 = QtWidgets.QLabel(self.widget)
        self.label_Z0.setObjectName("label_Z0")
        self.gridLayout_3.addWidget(self.label_Z0, 0, 0, 1, 1)
        self.dsB_Z0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_Z0.setObjectName("dsB_Z0")
        self.gridLayout_3.addWidget(self.dsB_Z0, 0, 1, 1, 1)
        self.label_Zrange = QtWidgets.QLabel(self.widget)
        self.label_Zrange.setObjectName("label_Zrange")
        self.gridLayout_3.addWidget(self.label_Zrange, 1, 0, 1, 1)
        self.dsB_Zrange = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsB_Zrange.setObjectName("dsB_Zrange")
        self.gridLayout_3.addWidget(self.dsB_Zrange, 1, 1, 1, 1)
        self.label_Zsteps = QtWidgets.QLabel(self.widget)
        self.label_Zsteps.setObjectName("label_Zsteps")
        self.gridLayout_3.addWidget(self.label_Zsteps, 2, 0, 1, 1)
        self.sB_Zsteps = QtWidgets.QSpinBox(self.widget)
        self.sB_Zsteps.setMinimum(1)
        self.sB_Zsteps.setObjectName("sB_Zsteps")
        self.gridLayout_3.addWidget(self.sB_Zsteps, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.viewZ = QtWidgets.QGraphicsView(self.widget)
        self.viewZ.setObjectName("viewZ")
        self.verticalLayout_4.addWidget(self.viewZ)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cB_detector = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_detector.sizePolicy().hasHeightForWidth())
        self.cB_detector.setSizePolicy(sizePolicy)
        self.cB_detector.setMinimumSize(QtCore.QSize(350, 0))
        self.cB_detector.setObjectName("cB_detector")
        self.horizontalLayout_2.addWidget(self.cB_detector)
        self.optimize_button = QtWidgets.QPushButton(self.splitter)
        self.optimize_button.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.optimize_button.setFont(font)
        self.optimize_button.setObjectName("optimize_button")
        self.verticalLayout_5.addWidget(self.splitter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Optimizer_title.setText(_translate("MainWindow", "Optimiser"))
        self.Xtitle.setText(_translate("MainWindow", "X-Axis"))
        self.label_X0.setText(_translate("MainWindow", "X0"))
        self.label_Xrange.setText(_translate("MainWindow", "X-range"))
        self.label_Xsteps.setText(_translate("MainWindow", "nr steps"))
        self.Ytitle.setText(_translate("MainWindow", "Y-Axis"))
        self.label_Y0.setText(_translate("MainWindow", "Y0"))
        self.label_Yrange.setText(_translate("MainWindow", "Y-range"))
        self.label_Ysteps.setText(_translate("MainWindow", "nr steps"))
        self.Ztitle.setText(_translate("MainWindow", "Z-Axis"))
        self.label_Z0.setText(_translate("MainWindow", "Z0"))
        self.label_Zrange.setText(_translate("MainWindow", "Z-range"))
        self.label_Zsteps.setText(_translate("MainWindow", "nr steps"))
        self.label.setText(_translate("MainWindow", "Detector"))
        self.optimize_button.setText(_translate("MainWindow", "Optimise"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

