# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starlightCapture.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_starlightCapture(object):
    def setupUi(self, starlightCapture):
        starlightCapture.setObjectName(_fromUtf8("starlightCapture"))
        starlightCapture.resize(964, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        starlightCapture.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(starlightCapture)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.autolevelsBox = QtGui.QCheckBox(starlightCapture)
        self.autolevelsBox.setChecked(True)
        self.autolevelsBox.setObjectName(_fromUtf8("autolevelsBox"))
        self.verticalLayout_2.addWidget(self.autolevelsBox)
        self.eqHistBox = QtGui.QCheckBox(starlightCapture)
        self.eqHistBox.setObjectName(_fromUtf8("eqHistBox"))
        self.verticalLayout_2.addWidget(self.eqHistBox)
        self.horizFlipCheckBox = QtGui.QCheckBox(starlightCapture)
        self.horizFlipCheckBox.setObjectName(_fromUtf8("horizFlipCheckBox"))
        self.verticalLayout_2.addWidget(self.horizFlipCheckBox)
        self.vertFlipCheckBox = QtGui.QCheckBox(starlightCapture)
        self.vertFlipCheckBox.setObjectName(_fromUtf8("vertFlipCheckBox"))
        self.verticalLayout_2.addWidget(self.vertFlipCheckBox)
        self.crossLinesCheckBox = QtGui.QCheckBox(starlightCapture)
        self.crossLinesCheckBox.setEnabled(True)
        self.crossLinesCheckBox.setChecked(False)
        self.crossLinesCheckBox.setObjectName(_fromUtf8("crossLinesCheckBox"))
        self.verticalLayout_2.addWidget(self.crossLinesCheckBox)
        self.crossLinesMaxCheckBox = QtGui.QCheckBox(starlightCapture)
        self.crossLinesMaxCheckBox.setObjectName(_fromUtf8("crossLinesMaxCheckBox"))
        self.verticalLayout_2.addWidget(self.crossLinesMaxCheckBox)
        self.setCrossLinesToMaxButton = QtGui.QPushButton(starlightCapture)
        self.setCrossLinesToMaxButton.setObjectName(_fromUtf8("setCrossLinesToMaxButton"))
        self.verticalLayout_2.addWidget(self.setCrossLinesToMaxButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcdAmplitude = QtGui.QLCDNumber(starlightCapture)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdAmplitude.sizePolicy().hasHeightForWidth())
        self.lcdAmplitude.setSizePolicy(sizePolicy)
        self.lcdAmplitude.setMinimumSize(QtCore.QSize(0, 50))
        self.lcdAmplitude.setObjectName(_fromUtf8("lcdAmplitude"))
        self.gridLayout_2.addWidget(self.lcdAmplitude, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(starlightCapture)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.lcdFwhm = QtGui.QLCDNumber(starlightCapture)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdFwhm.sizePolicy().hasHeightForWidth())
        self.lcdFwhm.setSizePolicy(sizePolicy)
        self.lcdFwhm.setMinimumSize(QtCore.QSize(0, 50))
        self.lcdFwhm.setProperty("value", 0.0)
        self.lcdFwhm.setObjectName(_fromUtf8("lcdFwhm"))
        self.gridLayout_2.addWidget(self.lcdFwhm, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(starlightCapture)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.satIndicator = QtGui.QLabel(starlightCapture)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.satIndicator.setFont(font)
        self.satIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.satIndicator.setObjectName(_fromUtf8("satIndicator"))
        self.verticalLayout.addWidget(self.satIndicator)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(starlightCapture)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cameraID = QtGui.QSpinBox(starlightCapture)
        self.cameraID.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cameraID.setObjectName(_fromUtf8("cameraID"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cameraID)
        self.label_4 = QtGui.QLabel(starlightCapture)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.modelName = QtGui.QLineEdit(starlightCapture)
        self.modelName.setEnabled(False)
        self.modelName.setObjectName(_fromUtf8("modelName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.modelName)
        self.label = QtGui.QLabel(starlightCapture)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.exposureTime = QtGui.QDoubleSpinBox(starlightCapture)
        self.exposureTime.setDecimals(3)
        self.exposureTime.setMinimum(0.001)
        self.exposureTime.setMaximum(3600.0)
        self.exposureTime.setSingleStep(0.1)
        self.exposureTime.setProperty("value", 0.01)
        self.exposureTime.setObjectName(_fromUtf8("exposureTime"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.exposureTime)
        self.label_5 = QtGui.QLabel(starlightCapture)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ilAcq = QtGui.QCheckBox(starlightCapture)
        self.ilAcq.setEnabled(False)
        self.ilAcq.setText(_fromUtf8(""))
        self.ilAcq.setObjectName(_fromUtf8("ilAcq"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ilAcq)
        self.label_6 = QtGui.QLabel(starlightCapture)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.ilDoubleExpo = QtGui.QCheckBox(starlightCapture)
        self.ilDoubleExpo.setEnabled(False)
        self.ilDoubleExpo.setText(_fromUtf8(""))
        self.ilDoubleExpo.setObjectName(_fromUtf8("ilDoubleExpo"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ilDoubleExpo)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(starlightCapture)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.selectFileLineEdit = QtGui.QLineEdit(starlightCapture)
        self.selectFileLineEdit.setObjectName(_fromUtf8("selectFileLineEdit"))
        self.horizontalLayout_3.addWidget(self.selectFileLineEdit)
        self.selectFileBut = QtGui.QPushButton(starlightCapture)
        self.selectFileBut.setMinimumSize(QtCore.QSize(60, 0))
        self.selectFileBut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectFileBut.setObjectName(_fromUtf8("selectFileBut"))
        self.horizontalLayout_3.addWidget(self.selectFileBut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.captureBox = QtGui.QCheckBox(starlightCapture)
        self.captureBox.setObjectName(_fromUtf8("captureBox"))
        self.verticalLayout.addWidget(self.captureBox)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startBut = QtGui.QPushButton(starlightCapture)
        self.startBut.setObjectName(_fromUtf8("startBut"))
        self.horizontalLayout_2.addWidget(self.startBut)
        self.stopBut = QtGui.QPushButton(starlightCapture)
        self.stopBut.setObjectName(_fromUtf8("stopBut"))
        self.horizontalLayout_2.addWidget(self.stopBut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtGui.QProgressBar(starlightCapture)
        self.progressBar.setEnabled(True)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 15))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.image = ImageView(starlightCapture)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(600, 450))
        self.image.setObjectName(_fromUtf8("image"))
        self.gridLayout.addWidget(self.image, 0, 2, 1, 1)

        self.retranslateUi(starlightCapture)
        QtCore.QMetaObject.connectSlotsByName(starlightCapture)

    def retranslateUi(self, starlightCapture):
        starlightCapture.setWindowTitle(_translate("starlightCapture", "Starlight Capture", None))
        self.autolevelsBox.setText(_translate("starlightCapture", "Auto-levels", None))
        self.eqHistBox.setText(_translate("starlightCapture", "Equalize histogram", None))
        self.horizFlipCheckBox.setText(_translate("starlightCapture", "Horizontal flipping", None))
        self.vertFlipCheckBox.setText(_translate("starlightCapture", "Vertical flipping", None))
        self.crossLinesCheckBox.setText(_translate("starlightCapture", "Cross lines (manual marker)", None))
        self.crossLinesMaxCheckBox.setText(_translate("starlightCapture", "Cross lines (auto center of mass)", None))
        self.setCrossLinesToMaxButton.setText(_translate("starlightCapture", "Set marker to center of mass", None))
        self.label_7.setText(_translate("starlightCapture", "MAX - MIN", None))
        self.label_8.setText(_translate("starlightCapture", "FWHM", None))
        self.satIndicator.setText(_translate("starlightCapture", "SATURATING", None))
        self.label_2.setText(_translate("starlightCapture", "Camera ID number:", None))
        self.label_4.setText(_translate("starlightCapture", "Camera model:", None))
        self.label.setText(_translate("starlightCapture", "Exposure time (s):", None))
        self.label_5.setText(_translate("starlightCapture", "InterLacing acq.:", None))
        self.label_6.setText(_translate("starlightCapture", "IL corr double expo:", None))
        self.label_3.setText(_translate("starlightCapture", "Saving directory:", None))
        self.selectFileBut.setText(_translate("starlightCapture", "Select", None))
        self.captureBox.setText(_translate("starlightCapture", "Capture", None))
        self.startBut.setText(_translate("starlightCapture", "Start", None))
        self.stopBut.setText(_translate("starlightCapture", "Stop", None))

from pyqtgraph import ImageView
