# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Daniel\Desktop\PhD\Python\QuantumPhotonicsLab\measurements\libs\scan_gui_ctrl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(255, 663)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_steps = QtWidgets.QLabel(self.centralwidget)
        self.label_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_steps.setObjectName("label_steps")
        self.gridLayout_2.addWidget(self.label_steps, 2, 2, 1, 1)
        self.label_max = QtWidgets.QLabel(self.centralwidget)
        self.label_max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max.setObjectName("label_max")
        self.gridLayout_2.addWidget(self.label_max, 2, 1, 1, 1)
        self.label_min = QtWidgets.QLabel(self.centralwidget)
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.gridLayout_2.addWidget(self.label_min, 2, 0, 1, 1)
        self.dsB_min1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_min1.setDecimals(2)
        self.dsB_min1.setMinimum(-10.0)
        self.dsB_min1.setMaximum(10.0)
        self.dsB_min1.setSingleStep(0.01)
        self.dsB_min1.setObjectName("dsB_min1")
        self.gridLayout_2.addWidget(self.dsB_min1, 4, 0, 1, 1)
        self.dsB_max1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_max1.setMinimum(-10.0)
        self.dsB_max1.setMaximum(10.0)
        self.dsB_max1.setSingleStep(0.01)
        self.dsB_max1.setObjectName("dsB_max1")
        self.gridLayout_2.addWidget(self.dsB_max1, 4, 1, 1, 1)
        self.dsB_steps1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_steps1.setDecimals(0)
        self.dsB_steps1.setMinimum(0.0)
        self.dsB_steps1.setMaximum(20.0)
        self.dsB_steps1.setSingleStep(0.0001)
        self.dsB_steps1.setObjectName("dsB_steps1")
        self.gridLayout_2.addWidget(self.dsB_steps1, 4, 2, 1, 1)
        self.dsB_min2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_min2.setMinimum(-10.0)
        self.dsB_min2.setMaximum(10.0)
        self.dsB_min2.setSingleStep(0.01)
        self.dsB_min2.setObjectName("dsB_min2")
        self.gridLayout_2.addWidget(self.dsB_min2, 6, 0, 1, 1)
        self.dsB_max2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_max2.setMinimum(-10.0)
        self.dsB_max2.setMaximum(10.0)
        self.dsB_max2.setSingleStep(0.01)
        self.dsB_max2.setObjectName("dsB_max2")
        self.gridLayout_2.addWidget(self.dsB_max2, 6, 1, 1, 1)
        self.dsB_steps2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_steps2.setDecimals(0)
        self.dsB_steps2.setMinimum(0.0)
        self.dsB_steps2.setMaximum(20.0)
        self.dsB_steps2.setSingleStep(0.0001)
        self.dsB_steps2.setObjectName("dsB_steps2")
        self.gridLayout_2.addWidget(self.dsB_steps2, 6, 2, 1, 1)
        self.dsB_fixed_pos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsB_fixed_pos.setMinimum(-10.0)
        self.dsB_fixed_pos.setMaximum(10.0)
        self.dsB_fixed_pos.setSingleStep(0.01)
        self.dsB_fixed_pos.setObjectName("dsB_fixed_pos")
        self.gridLayout_2.addWidget(self.dsB_fixed_pos, 8, 0, 1, 1)
        self.cB_scanner2 = QtWidgets.QComboBox(self.centralwidget)
        self.cB_scanner2.setObjectName("cB_scanner2")
        self.gridLayout_2.addWidget(self.cB_scanner2, 5, 0, 1, 3)
        self.cB_scanner1 = QtWidgets.QComboBox(self.centralwidget)
        self.cB_scanner1.setObjectName("cB_scanner1")
        self.gridLayout_2.addWidget(self.cB_scanner1, 3, 0, 1, 3)
        self.cB_scanner3 = QtWidgets.QComboBox(self.centralwidget)
        self.cB_scanner3.setObjectName("cB_scanner3")
        self.gridLayout_2.addWidget(self.cB_scanner3, 7, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_ycurr = QtWidgets.QLabel(self.centralwidget)
        self.label_ycurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ycurr.setObjectName("label_ycurr")
        self.gridLayout_3.addWidget(self.label_ycurr, 1, 1, 1, 1)
        self.label_xcurr = QtWidgets.QLabel(self.centralwidget)
        self.label_xcurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xcurr.setObjectName("label_xcurr")
        self.gridLayout_3.addWidget(self.label_xcurr, 1, 0, 1, 1)
        self.label_zcurr = QtWidgets.QLabel(self.centralwidget)
        self.label_zcurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zcurr.setObjectName("label_zcurr")
        self.gridLayout_3.addWidget(self.label_zcurr, 1, 2, 1, 1)
        self.label_view_xCurr = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_xCurr.setFont(font)
        self.label_view_xCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_xCurr.setObjectName("label_view_xCurr")
        self.gridLayout_3.addWidget(self.label_view_xCurr, 2, 0, 1, 1)
        self.label_view_yCurr = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_yCurr.setFont(font)
        self.label_view_yCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_yCurr.setObjectName("label_view_yCurr")
        self.gridLayout_3.addWidget(self.label_view_yCurr, 2, 1, 1, 1)
        self.label_view_zCurr = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_zCurr.setFont(font)
        self.label_view_zCurr.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.label_view_zCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_zCurr.setObjectName("label_view_zCurr")
        self.gridLayout_3.addWidget(self.label_view_zCurr, 2, 2, 1, 1)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 0, 0, 1, 2)
        self.label_done = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_done.setFont(font)
        self.label_done.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_done.setObjectName("label_done")
        self.gridLayout_3.addWidget(self.label_done, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.gridLayout.addWidget(self.pushButton_Start, 1, 0, 1, 1)
        self.label_detectors = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_detectors.setFont(font)
        self.label_detectors.setObjectName("label_detectors")
        self.gridLayout.addWidget(self.label_detectors, 1, 1, 1, 1)
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.gridLayout.addWidget(self.pushButton_Stop, 2, 0, 1, 1)
        self.cb_detector = QtWidgets.QComboBox(self.centralwidget)
        self.cb_detector.setObjectName("cb_detector")
        self.gridLayout.addWidget(self.cb_detector, 2, 1, 1, 1)
        self.pushButton_Resume = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Resume.setObjectName("pushButton_Resume")
        self.gridLayout.addWidget(self.pushButton_Resume, 3, 0, 1, 1)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 4, 0, 1, 1)
        self.sB_APD = QtWidgets.QSpinBox(self.centralwidget)
        self.sB_APD.setMaximum(99999)
        self.sB_APD.setObjectName("sB_APD")
        self.gridLayout.addWidget(self.sB_APD, 4, 1, 1, 1)
        self.label_APD = QtWidgets.QLabel(self.centralwidget)
        self.label_APD.setObjectName("label_APD")
        self.gridLayout.addWidget(self.label_APD, 3, 1, 1, 1)
        self.checkBox_autosave = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autosave.setChecked(True)
        self.checkBox_autosave.setObjectName("checkBox_autosave")
        self.gridLayout.addWidget(self.checkBox_autosave, 5, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_optimizer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_optimizer.setObjectName("pushButton_optimizer")
        self.verticalLayout.addWidget(self.pushButton_optimizer)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 255, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_steps.setText(_translate("MainWindow", "steps"))
        self.label_max.setText(_translate("MainWindow", "max"))
        self.label_min.setText(_translate("MainWindow", "min"))
        self.label_2.setText(_translate("MainWindow", "Scan Controller"))
        self.label_ycurr.setText(_translate("MainWindow", "y (curr)"))
        self.label_xcurr.setText(_translate("MainWindow", "x (curr)"))
        self.label_zcurr.setText(_translate("MainWindow", "z  (curr)"))
        self.label_view_xCurr.setText(_translate("MainWindow", "---"))
        self.label_view_yCurr.setText(_translate("MainWindow", "---"))
        self.label_view_zCurr.setText(_translate("MainWindow", "---"))
        self.label_status.setText(_translate("MainWindow", "Idle"))
        self.label_done.setText(_translate("MainWindow", "0/0"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.label_detectors.setText(_translate("MainWindow", "Detectors"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Resume.setText(_translate("MainWindow", "Resume"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.label_APD.setText(_translate("MainWindow", "integr time (ms)"))
        self.checkBox_autosave.setText(_translate("MainWindow", "scan auto-save "))
        self.pushButton_optimizer.setText(_translate("MainWindow", "Optimizer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

