# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cristian\Research\QPL-code\measurements\libs\scan_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 741)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 700, 700))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(720, 140, 241, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_min = QtWidgets.QLabel(self.layoutWidget)
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.gridLayout_2.addWidget(self.label_min, 0, 1, 1, 1)
        self.label_max = QtWidgets.QLabel(self.layoutWidget)
        self.label_max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max.setObjectName("label_max")
        self.gridLayout_2.addWidget(self.label_max, 0, 2, 1, 1)
        self.label_steps = QtWidgets.QLabel(self.layoutWidget)
        self.label_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_steps.setObjectName("label_steps")
        self.gridLayout_2.addWidget(self.label_steps, 0, 3, 1, 1)
        self.cb_scan1 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_scan1.setFont(font)
        self.cb_scan1.setObjectName("cb_scan1")
        self.cb_scan1.addItem("")
        self.cb_scan1.addItem("")
        self.cb_scan1.addItem("")
        self.gridLayout_2.addWidget(self.cb_scan1, 1, 0, 1, 1)
        self.dsB_min1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_min1.setObjectName("dsB_min1")
        self.gridLayout_2.addWidget(self.dsB_min1, 1, 1, 1, 1)
        self.dsB_max1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_max1.setObjectName("dsB_max1")
        self.gridLayout_2.addWidget(self.dsB_max1, 1, 2, 1, 1)
        self.dsB_steps1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_steps1.setDecimals(0)
        self.dsB_steps1.setMinimum(1.0)
        self.dsB_steps1.setMaximum(1000.0)
        self.dsB_steps1.setObjectName("dsB_steps1")
        self.gridLayout_2.addWidget(self.dsB_steps1, 1, 3, 1, 1)
        self.cb_scan2 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_scan2.setFont(font)
        self.cb_scan2.setObjectName("cb_scan2")
        self.cb_scan2.addItem("")
        self.cb_scan2.addItem("")
        self.cb_scan2.addItem("")
        self.gridLayout_2.addWidget(self.cb_scan2, 2, 0, 1, 1)
        self.dsB_min2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_min2.setObjectName("dsB_min2")
        self.gridLayout_2.addWidget(self.dsB_min2, 2, 1, 1, 1)
        self.dsB_max2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_max2.setObjectName("dsB_max2")
        self.gridLayout_2.addWidget(self.dsB_max2, 2, 2, 1, 1)
        self.dsB_steps2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_steps2.setDecimals(0)
        self.dsB_steps2.setMinimum(1.0)
        self.dsB_steps2.setMaximum(1000.0)
        self.dsB_steps2.setObjectName("dsB_steps2")
        self.gridLayout_2.addWidget(self.dsB_steps2, 2, 3, 1, 1)
        self.cb_fixed = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_fixed.setObjectName("cb_fixed")
        self.cb_fixed.addItem("")
        self.cb_fixed.addItem("")
        self.cb_fixed.addItem("")
        self.gridLayout_2.addWidget(self.cb_fixed, 3, 0, 1, 1)
        self.dsB_fixed_pos = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsB_fixed_pos.setObjectName("dsB_fixed_pos")
        self.gridLayout_2.addWidget(self.dsB_fixed_pos, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_ycurr = QtWidgets.QLabel(self.layoutWidget)
        self.label_ycurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ycurr.setObjectName("label_ycurr")
        self.gridLayout_3.addWidget(self.label_ycurr, 0, 1, 1, 1)
        self.label_xcurr = QtWidgets.QLabel(self.layoutWidget)
        self.label_xcurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xcurr.setObjectName("label_xcurr")
        self.gridLayout_3.addWidget(self.label_xcurr, 0, 0, 1, 1)
        self.label_zcurr = QtWidgets.QLabel(self.layoutWidget)
        self.label_zcurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zcurr.setObjectName("label_zcurr")
        self.gridLayout_3.addWidget(self.label_zcurr, 0, 2, 1, 1)
        self.label_view_xCurr = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_xCurr.setFont(font)
        self.label_view_xCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_xCurr.setObjectName("label_view_xCurr")
        self.gridLayout_3.addWidget(self.label_view_xCurr, 1, 0, 1, 1)
        self.label_view_yCurr = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_yCurr.setFont(font)
        self.label_view_yCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_yCurr.setObjectName("label_view_yCurr")
        self.gridLayout_3.addWidget(self.label_view_yCurr, 1, 1, 1, 1)
        self.label_view_zCurr = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view_zCurr.setFont(font)
        self.label_view_zCurr.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.label_view_zCurr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_view_zCurr.setObjectName("label_view_zCurr")
        self.gridLayout_3.addWidget(self.label_view_zCurr, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(228, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_APD = QtWidgets.QLabel(self.layoutWidget)
        self.label_APD.setObjectName("label_APD")
        self.horizontalLayout.addWidget(self.label_APD)
        self.sB_APD = QtWidgets.QSpinBox(self.layoutWidget)
        self.sB_APD.setObjectName("sB_APD")
        self.horizontalLayout.addWidget(self.sB_APD)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(228, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.gridLayout.addWidget(self.pushButton_Start, 0, 0, 1, 1)
        self.label_detectors = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_detectors.setFont(font)
        self.label_detectors.setObjectName("label_detectors")
        self.gridLayout.addWidget(self.label_detectors, 0, 1, 1, 1)
        self.pushButton_Stop = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.gridLayout.addWidget(self.pushButton_Stop, 1, 0, 1, 1)
        self.cb_detector = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_detector.setObjectName("cb_detector")
        self.gridLayout.addWidget(self.cb_detector, 1, 1, 1, 1)
        self.pushButton_Resume = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Resume.setObjectName("pushButton_Resume")
        self.gridLayout.addWidget(self.pushButton_Resume, 2, 0, 1, 1)
        self.pushButton_Save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_min.setText(_translate("Form", "min"))
        self.label_max.setText(_translate("Form", "max"))
        self.label_steps.setText(_translate("Form", "steps"))
        self.cb_scan1.setItemText(0, _translate("Form", "x"))
        self.cb_scan1.setItemText(1, _translate("Form", "y"))
        self.cb_scan1.setItemText(2, _translate("Form", "z"))
        self.cb_scan2.setCurrentText(_translate("Form", "x"))
        self.cb_scan2.setItemText(0, _translate("Form", "x"))
        self.cb_scan2.setItemText(1, _translate("Form", "y"))
        self.cb_scan2.setItemText(2, _translate("Form", "z"))
        self.cb_fixed.setItemText(0, _translate("Form", "x"))
        self.cb_fixed.setItemText(1, _translate("Form", "y"))
        self.cb_fixed.setItemText(2, _translate("Form", "z"))
        self.label_ycurr.setText(_translate("Form", "y (curr)"))
        self.label_xcurr.setText(_translate("Form", "x (curr)"))
        self.label_zcurr.setText(_translate("Form", "z  (curr)"))
        self.label_view_xCurr.setText(_translate("Form", "---"))
        self.label_view_yCurr.setText(_translate("Form", "---"))
        self.label_view_zCurr.setText(_translate("Form", "---"))
        self.label_APD.setText(_translate("Form", "APD integr time (ms)"))
        self.pushButton_Start.setText(_translate("Form", "Start"))
        self.label_detectors.setText(_translate("Form", "Detector"))
        self.pushButton_Stop.setText(_translate("Form", "Stop"))
        self.pushButton_Resume.setText(_translate("Form", "Resume"))
        self.pushButton_Save.setText(_translate("Form", "Save"))

