
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import h5py
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as Canvas
from matplotlib.figure import Figure
from measurements.libs.QPLser import StreamCanvas as SC
import random

from importlib import reload
reload (SC)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(1155, 754)
        self.vbl = QtWidgets.QVBoxLayout(Panel)
        self.vbl.setContentsMargins(0,0,0,0)
        self.canvas = SC.MultiStreamCanvas(Panel, width=7, height=3, dpi=200)
        self.vbl.addWidget (self.canvas)
        self.Hscrollbar = QtWidgets.QScrollBar(Panel)
        self.Hscrollbar.setGeometry(QtCore.QRect(10, 590, 1131, 21))
        self.Hscrollbar.setPageStep(50)
        self.Hscrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.Hscrollbar.setObjectName("Hscrollbar")
        self.label_view_time = QtWidgets.QLabel(Panel)
        self.label_view_time.setGeometry(QtCore.QRect(410, 660, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_view_time.setFont(font)
        self.label_view_time.setObjectName("label_view_time")
        self.cb_D2 = QtWidgets.QCheckBox(Panel)
        self.cb_D2.setGeometry(QtCore.QRect(80, 713, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D2.setFont(font)
        self.cb_D2.setObjectName("cb_D2")
        self.cb_A0 = QtWidgets.QCheckBox(Panel)
        self.cb_A0.setGeometry(QtCore.QRect(260, 713, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_A0.setFont(font)
        self.cb_A0.setObjectName("cb_A0")
        self.botton_zoom_in = QtWidgets.QPushButton(Panel)
        self.botton_zoom_in.setGeometry(QtCore.QRect(560, 700, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.botton_zoom_in.setFont(font)
        self.botton_zoom_in.setObjectName("botton_zoom_in")
        self.cb_D7 = QtWidgets.QCheckBox(Panel)
        self.cb_D7.setGeometry(QtCore.QRect(200, 733, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D7.setFont(font)
        self.cb_D7.setObjectName("cb_D7")
        self.sb_rep_nr = QtWidgets.QSpinBox(Panel)
        self.sb_rep_nr.setGeometry(QtCore.QRect(90, 663, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.sb_rep_nr.setFont(font)
        self.sb_rep_nr.setObjectName("sb_rep_nr")
        self.button_full_view = QtWidgets.QPushButton(Panel)
        self.button_full_view.setGeometry(QtCore.QRect(410, 700, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.button_full_view.setFont(font)
        self.button_full_view.setObjectName("button_full_view")
        self.cb_D3 = QtWidgets.QCheckBox(Panel)
        self.cb_D3.setGeometry(QtCore.QRect(80, 733, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D3.setFont(font)
        self.cb_D3.setObjectName("cb_D3")
        self.cb_D5 = QtWidgets.QCheckBox(Panel)
        self.cb_D5.setGeometry(QtCore.QRect(140, 733, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D5.setFont(font)
        self.cb_D5.setObjectName("cb_D5")
        self.label_repNr = QtWidgets.QLabel(Panel)
        self.label_repNr.setGeometry(QtCore.QRect(20, 663, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_repNr.setFont(font)
        self.label_repNr.setObjectName("label_repNr")
        self.cb_D4 = QtWidgets.QCheckBox(Panel)
        self.cb_D4.setGeometry(QtCore.QRect(140, 713, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D4.setFont(font)
        self.cb_D4.setObjectName("cb_D4")
        self.label_fileTag = QtWidgets.QLabel(Panel)
        self.label_fileTag.setGeometry(QtCore.QRect(870, 683, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_fileTag.setFont(font)
        self.label_fileTag.setObjectName("label_fileTag")
        self.cb_A1 = QtWidgets.QCheckBox(Panel)
        self.cb_A1.setGeometry(QtCore.QRect(260, 733, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_A1.setFont(font)
        self.cb_A1.setObjectName("cb_A1")
        self.lineEdit_fileTag = QtWidgets.QLineEdit(Panel)
        self.lineEdit_fileTag.setGeometry(QtCore.QRect(940, 683, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_fileTag.setFont(font)
        self.lineEdit_fileTag.setObjectName("lineEdit_fileTag")
        self.cb_D6 = QtWidgets.QCheckBox(Panel)
        self.cb_D6.setGeometry(QtCore.QRect(200, 713, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D6.setFont(font)
        self.cb_D6.setObjectName("cb_D6")
        self.label_nr_steps_finelaser_2 = QtWidgets.QLabel(Panel)
        self.label_nr_steps_finelaser_2.setGeometry(QtCore.QRect(20, 620, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_nr_steps_finelaser_2.setFont(font)
        self.label_nr_steps_finelaser_2.setObjectName("label_nr_steps_finelaser_2")
        self.button_zoom_out = QtWidgets.QPushButton(Panel)
        self.button_zoom_out.setGeometry(QtCore.QRect(640, 700, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_zoom_out.setFont(font)
        self.button_zoom_out.setObjectName("button_zoom_out")
        self.cb_D1 = QtWidgets.QCheckBox(Panel)
        self.cb_D1.setGeometry(QtCore.QRect(20, 733, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D1.setFont(font)
        self.cb_D1.setObjectName("cb_D1")
        self.button_save = QtWidgets.QPushButton(Panel)
        self.button_save.setGeometry(QtCore.QRect(940, 645, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.button_save.setFont(font)
        self.button_save.setObjectName("button_save")
        self.cb_D0 = QtWidgets.QCheckBox(Panel)
        self.cb_D0.setGeometry(QtCore.QRect(20, 710, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cb_D0.setFont(font)
        self.cb_D0.setObjectName("cb_D0")

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Panel"))
        self.label_view_time.setText(_translate("Panel", "Zoom"))
        self.cb_D2.setText(_translate("Panel", "D2"))
        self.cb_A0.setText(_translate("Panel", "A0"))
        self.botton_zoom_in.setText(_translate("Panel", "+"))
        self.cb_D7.setText(_translate("Panel", "D7"))
        self.button_full_view.setText(_translate("Panel", "Full View"))
        self.cb_D3.setText(_translate("Panel", "D3"))
        self.cb_D5.setText(_translate("Panel", "D5"))
        self.label_repNr.setText(_translate("Panel", "Rep nr"))
        self.cb_D4.setText(_translate("Panel", "D4"))
        self.label_fileTag.setText(_translate("Panel", "file tag:"))
        self.cb_A1.setText(_translate("Panel", "A1"))
        self.cb_D6.setText(_translate("Panel", "D6"))
        self.label_nr_steps_finelaser_2.setText(_translate("Panel", "QPLser - Stream Viewer"))
        self.button_zoom_out.setText(_translate("Panel", "-"))
        self.cb_D1.setText(_translate("Panel", "D1"))
        self.button_save.setText(_translate("Panel", "SAVE view"))
        self.cb_D0.setText(_translate("Panel", "D0"))

